### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [transactiveltd/uk-modulus-checking#1]
@jbeeko has written:

> We need a modulus checking library. As described on this site:
> https://www.vocalink.com/customer-support/modulus-checking/
> 
> The algorithm is described by this document 
> https://www.vocalink.com/media/3004/vocalink-validating-account-numbers-v490.pdf
> 
> And and the data in these files:
> https://www.vocalink.com/media/3003/valacdos-v490.txt
> https://www.vocalink.com/media/1517/scsubtab.txt
> 
> There is a very simple implementation of what is known as the "Standard 10" method here: 
> https://github.com/transactiveltd/Seymour/blob/4691193c8c4672c2a0b0d5ed310613bef1c04631/src/Transactive.Seymour.Server.Domain.Clearbank/ClearBankAccount.fs#L19-L41
> 
> There is an incomplete Python implementation here: https://github.com/bazerk/uk-modulus-checking
> 
> Requirements checking & generating:
> * Load date from external data source to model in memory
> * Check a sortcode/account number and return either pass, given the data sets.
> * Generate a check digit from a sortcode and 7 digits of info given a specified algorithm and weights. This should not require the data set.
> 
---
Moved from https://github.com/transactiveltd/Seymour/issues/767

**Comment by bartsokol** [comment]
How do we want to name the library? The repo name doesn't fit into typical .NET assembly / NuGet name. I used temporary name AccountNoValidator, but before I'll create the PR I'd like to give it a proper name.

**Comment by jbeeko** [comment]
What is nugget naming convention? Camel case? UkModulusCheck then? I’m open to suggestions.

I think being explicit that this is a modulus check is better than validation.  The reason is some libraries with access to private info do more than just a modulus check.

On Jun 27, 2018, at 12:12 PM, Bart Sokol <notifications@github.com<mailto:notifications@github.com>> wrote:


How do we want to name the library? The repo name doesn't fit into typical .NET assembly / NuGet name. I used temporary name AccountNoValidator, but before I'll create the PR I'd like to give it a proper name.

**Comment by bartsokol** [comment]
Thanks @jbeeko, UkModulusCheck will be fine, I'll change everything accordingly.

**Comment by bartsokol** [comment]
Regarding the last part of the task:
"Generate a check digit from a sortcode and 7 digits of info given a specified algorithm and weights. This should not require the data set."
Can someone elaborate on this? What kind of check digit should be calculated (which algorithms should be used)? For the other part of the task there is usually SC/AN pair where AN is 8 digits, and in most cases, there is no check digit used (apart from few exceptions).

For now I have function signature like this:
`let calculateChecksum (method: ValidationMethod) (weightings: Weight list) (sortCode: SortCode) (accountNo: AccountNumber)`
I'm not sure what the output should be in this case.

**Comment by jbeeko** [comment]
When I need some external validation I've been using this site: https://www.sortcodes.co.uk

**Comment by bartsokol** [comment]
OK, so, if I understand correctly, you need to get a proper account number given the weightings, sort code and the (fragment of) account number. This may be a bit tricky. Trying to add a missing digit at the end could be the easiest way unless there are no exceptions and the weight at the end is 1. For any other position, adding the missing digit in the account number will move weighting positions and mess up with the checksum.

If you don't care what the sort code is then we can use sort code ranges from the VocaLink specs where 1 is the last number in the weightings and the algorithm is MOD10, e.g.:
`040082 040082 MOD10    2    1    2    1    2    1    0   64   32   16    8    4    2    1`
In this case, if you'll provide 040082 / 8447431 to the function, it can add 6 at the end of the account number and the check will pass.

If you need it for any/specific sort code where we have different weights/algorithms then it will be quite tricky - the easiest would be to generate the whole (possibly random) account number knowing the sort code and weights.

**Comment by jbeeko** [comment]
@bartsokol 
>OK, so, if I understand correctly, you need to get a proper account number given the 
>weightings, sort code and the (fragment of) account number. This may be a bit tricky. 

The strategy I've been using for where we need to generate an account number for ClearBank is to generate a random 7 digit number and then go through the sequence {0..9} finding the first digit which when appended results in an account number that passes based on the rules for the given sort code. In some cases for a non-zero weight there is no such digit. I just arbitrarily picked the last digit as the digit to modify. That one seems to usually be 0, 1 or -1. 

What I don't know is how to handle cases, if there are any, where two algorithms need to be executed one after the other.

**Comment by jbeeko** [comment]
Lets put this "account number building" requirement aside for the moment. I don't think it will see much use by third parties and in our case we only need to do it for a single bank.

**Comment by bartsokol** [comment]
OK, I'll remove the function from initial implementation then and we can approach it as a separate task.

BTW, in case of this particular sort code, if the 8th digit would be in the first position of the account number, it should be pretty easy - the weight there is 1, so if you start with '0' + generated number and then try the next digits if it fails then it should work.
So basically you could substitute this line:
https://github.com/transactiveltd/Seymour/blob/4691193c8c4672c2a0b0d5ed310613bef1c04631/src/Transactive.Seymour.Server.Domain.Clearbank/ClearBankAccount.fs#L37
with:
`let acctNo = i.ToString() + acctBase`
