### ISSUE TITLE
Add C# API

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [transactiveltd/uk-modulus-checking#4]
As in title, add C# friendly API (no DUs, no curried functions etc)

**Comment by bartsokol** [comment]
I'm considering 2 variants of the API and not sure which one to choose.

First is static class with no internal state, so basically the same API as in F# but more C#-friendly:

    var sortCode = "040469";
    var accountNumber = "12345678";

    try
    {
        var rules = Validator.LoadRules(@"C:\work\Transactive\uk-modulus-checking\data\valacdos-v490.txt");
        var substitutions = Validator.LoadSubstitutions(@"C:\work\Transactive\uk-modulus-checking\data\scsubtab.txt");

        var result = Validator.ValidateAccountNo(rules, substitutions, sortCode, accountNumber);

        if (result.IsValid)
            Console.WriteLine($"{sortCode}-{accountNumber} is valid :)");
        else
            Console.WriteLine($"{sortCode}-{accountNumber} is Invalid :( Reason: {result.FailureReason}");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error loading data from files: {ex}");
    }

The other option is to create an instance of the class and keep rules and substitutions as internal state of the class:

    var sortCode = "040469";
    var accountNumber = "12345678";
    var validator = new Validator();

    try
    {
        validator.LoadRules(@"C:\work\Transactive\uk-modulus-checking\data\valacdos-v490.txt");
        validator.LoadSubstitutions(@"C:\work\Transactive\uk-modulus-checking\data\scsubtab.txt");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error loading data from files: {ex}");
    }
    
    // no need to pass rules/substitutions as params
    var result = validator.ValidateAccountNo(sortCode, accountNumber);

    if (result.IsValid)
        Console.WriteLine($"{sortCode}-{accountNumber} is valid :)");
    else
        Console.WriteLine($"{sortCode}-{accountNumber} is Invalid :( Reason: {result.FailureReason}");

Any preferences regarding this @jbeeko @Krzysztof-Cieslak?

**Comment by Krzysztof-Cieslak** [comment]
I’d go with second option... but my knowledge of C# API design is non existent ;-)

**Comment by bartsokol** [comment]
I'm a bit skewed here as I usually write more "functional-like" code in C#, but I guess the second option will be more natural for most C# devs. I'll change it to the stateful approach.

**Comment by jbeeko** [comment]
I don’t know if this has been decided but my vote would be for option 2. Because I think that is more in line with OO thinking. You create an object, configure it as needed and then use it repeatedly. For example, HttpClient where you the pattern is to create one with a base URL and default headers and then use it again and again.

But I have never programmed in C#. Perhaps ask Warren on Slack
